export GOOGLE_APPLICATION_CREDENTIALS=/home/g281508/workbench/keys/templatization-backend-storage.json
echo GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS

export KUBERNETES_CLIENT_MODE=LOCAL
echo KUBERNETES_CLIENT_MODE: $KUBERNETES_CLIENT_MODE

export KUBERNETES_API_BASE_PATH=https://34.55.252.235
echo KUBERNETES_API_BASE_PATH: $KUBERNETES_API_BASE_PATH

export KUBERNETES_CLIENT_CERT_PATH=/home/g281508/workbench/metric/gke-cluster-cert.crt
echo KUBERNETES_CLIENT_CERT_PATH: $KUBERNETES_CLIENT_CERT_PATH

mvn clean package
mvn clean spring-boot:run