spring.application.name=scaling

# GKE log-severity KPI settings
gke.log-severity.thread-pool-size=5
gke.log-severity.max-retries=4
gke.log-severity.initial-backoff-millis=1000
gke.log-severity.backoff-multiplier=2

gke.key-points.namespace-prefixes=ref-,core-,gke-data

# PLEASE MAKE SURE TO CREATE METRIC COSTCO ENV
gke.log-severity.metric-type=logging.googleapis.com/user/datatrack_noise

logging.level.org.springframework.web.servlet.PageNotFound=OFF
logging.level.org.springframework.web.servlet.DispatcherServlet=WARN


// ...existing properties...

# Kubernetes client mode: LOCAL (gcloud/GKE credentials) or IN_CLUSTER (mounted SA)
kubernetes.client-mode=LOCAL
	# In your Deployment spec
	#env:
	#  - name: KUBERNETES_CLIENT_MODE
	#    value: "IN_CLUSTER"

# Only used in LOCAL mode; leave blank in-cluster
kubernetes.api-base-path=https://34.55.252.235
#kubernetes.ca-cert-path=C:/Users/281508/Documents/CostCo/scaling/ca.crt

kubernetes.ca-cert-path=C:\Users\281508\Documents\PrivateCloudCode\GitHubCodes\ca.crt