spring.application.name=scaling


# GKE log-severity KPI settings
gke.log-severity.thread-pool-size=5
gke.log-severity.max-retries=4
gke.log-severity.initial-backoff-millis=1000
gke.log-severity.backoff-multiplier=2

gke.key-points.namespace-prefixes=ref-,core-,gke-