apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  namespace: gke-data-track-foundation
  labels:
    component: serviceaccount
  annotations:
    iam.gke.io/gcp-service-account: templatization-backend-storage@ust-gcp-costco-replatform-poc.iam.gserviceaccount.com
    description: "Workload Identity for Costco Vendor Management Service"
automountServiceAccountToken: false