apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-framework-config
  namespace: gke-data-track-foundation
data:

  DEFAULT_GCP_PROJECT_ID: "#{GCP_PROJECT_ID}"
  GCP_PROJECT_ID: "#{GCP_PROJECT_ID}"

  NAME_SPACE_PREFIX: "#{NAME_SPACE_PREFIX}"
  SEVERITY_METRIC: "#{SEVERITY_METRIC}"

  KUBERNETES_CLIENT_MODE: "#{KUBERNETES_CLIENT_MODE}"
  KUBERNETES_API_BASE_PATH: "#{KUBERNETES_API_BASE_PATH}"
  KUBERNETES_CLIENT_CERT_PATH: "#{KUBERNETES_CLIENT_CERT_PATH}"

  SPRING_DATASOURCE_URL: "#{SPRING_DATASOURCE_URL}"
  SPRING_DATASOURCE_USERNAME: "#{SPRING_DATASOURCE_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "#{SPRING_DATASOURCE_PASSWORD}"
  
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "#{SPRING_JPA_HIBERNATE_DIALECT}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "#{SPRING_JPA_HIBERNATE_DDL_AUTO}"
  SPRING_JPA_OPEN_IN_VIEW: "#{SPRING_JPA_OPEN_IN_VIEW}"

  CLOUD_SQL_INSTANCE: "#{CLOUD_SQL_INSTANCE}"
